server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/tasteHub?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/testHub?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234*ztt
  redis:
#    url: rediss://default:AWe_AAIjcDEyZjc0MzRkNDE4YTY0ODU4ODg5YmExMWY4NmU5MzQ4YnAxMA@learning-glider-26559.upstash.io:6379
#    host: learning-glider-26559.upstash.io
#    port: 6379
#    password: AWe_AAIjcDEyZjc0MzRkNDE4YTY0ODU4ODg5YmExMWY4NmU5MzQ4YnAxMA
#    ssl:
#      enabled: true
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # Ignore non-null fields during JSON processing
mybatis-plus:
  type-aliases-package: com.hmdp.entity # Alias scanning package
logging:
  level:
    com.hmdp: debug